<?php

/**
 * @file
 * Contains twig_breakpoint.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function twig_breakpoint_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the twig_breakpoint module.
    case 'help.page.twig_breakpoint':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Adds a twig extension to enable xdebug breakpoints in templates') . '</p>';

      return $output;
    default:
  }
}

